export const apiUrl = process.env.NODE_ENV !== 'production' ? 'http://localhost:5000/api' : 'somedeployURL' ;
export const LOCAL_STORAGE_TOKEN_NAME = 'user-admin';

export const SET_AUTH = 'SET_AUTH';

export const LOCAL_STORAGE_TOKEN_NAME_CLIENT = 'user';

export const SET_AUTH_CLIENT = 'SET_AUTH_CLIENT';

export const SUPPLIERS_LOADED_SUCCESS = 'SUPPLIERS_LOADED_SUCCESS';
export const SUPPLIERS_LOADED_FAIL = 'SUPPLIERS_LOADED_FAIL';
export const SUPPLIERS_ADDED = 'SUPPLIERS_ADDED';
export const SUPPLIERS_UPDATED = 'SUPPLIERS_UPDATED';
export const SUPPLIERS_DELETED = 'SUPPLIERS_DELETED';
export const SUPPLIERS_FIND = 'SUPPLIERS_FIND';

export const SUPPLIERS_INVOICE_LOADED_SUCCESS = 'SUPPLIERS_INVOICE_LOADED_SUCCESS';
export const SUPPLIERS_INVOICE_LOADED_FAIL = 'SUPPLIERS_INVOICE_LOADED_FAIL';
export const SUPPLIERS_INVOICE_ADDED = 'SUPPLIERS_INVOICE_ADDED';
export const SUPPLIERS_INVOICE_UPDATED = 'SUPPLIERS_INVOICE_UPDATED';
export const SUPPLIERS_INVOICE_DELETED = 'SUPPLIERS_INVOICE_DELETED';
export const SUPPLIERS_INVOICE_FIND = 'SUPPLIERS_INVOICE_FIND';

export const CATEGORY_PRODUCT_LOADED_SUCCESS = 'CATEGORY_PRODUCT_LOADED_SUCCESS';
export const CATEGORY_PRODUCT_LOADED_FAIL = 'CATEGORY_PRODUCT_LOADED_FAIL';
export const CATEGORY_PRODUCT_ADDED = 'CATEGORY_PRODUCT_ADDED';
export const CATEGORY_PRODUCT_UPDATED = 'CATEGORY_PRODUCT_UPDATED';
export const CATEGORY_PRODUCT_DELETED = 'CATEGORY_PRODUCT_DELETED';
export const CATEGORY_PRODUCT_FIND = 'CATEGORY_PRODUCT_FIND';

export const PRODUCT_LOADED_SUCCESS = 'PRODUCT_LOADED_SUCCESS';
export const PRODUCT_LOADED_FAIL = 'PRODUCT_LOADED_FAIL';
export const CATEGORY_PRODUCT_FIND_BY_ID_LOADED_SUCCESS = 'CATEGORY_PRODUCT_FIND_BY_ID_LOADED_SUCCESS';
export const CATEGORY_PRODUCT_FIND_BY_ID_LOADED_FAIL = 'CATEGORY_PRODUCT_FIND_BY_ID_LOADED_FAIL';
export const PRODUCT_ADDED = 'PRODUCT_ADDED';
export const PRODUCT_UPDATED = 'PRODUCT_UPDATED';
export const PRODUCT_DELETED = 'PRODUCT_DELETED';
export const PRODUCT_FIND = 'PRODUCT_FIND';
export const PRODUCTS_FIND = 'PRODUCTS_FIND';
export const PRODUCTS_LOADED_SUCCESS = 'PRODUCTS_LOADED_SUCCESS';
export const PRODUCTS_LOADED_FAIL = 'PRODUCTS_LOADED_FAIL';

export const PRODUCT_INVOICE_LOADED_SUCCESS = 'PRODUCT_INVOICE_LOADED_SUCCESS';
export const PRODUCT_INVOICE_LOADED_FAIL = 'PRODUCT_INVOICE_LOADED_FAIL';
export const PRODUCT_INVOICE_ADDED = 'PRODUCT_INVOICE_ADDED';
export const PRODUCT_INVOICE_UPDATED = 'PRODUCT_INVOICE_UPDATED';
export const PRODUCT_INVOICE_DELETED = 'PRODUCT_INVOICE_DELETED';
export const PRODUCT_INVOICE_FIND = 'PRODUCT_INVOICE_FIND';
